import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes | Uriel Spiridione",
  description: "Generated by USpiri",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark bg-neutral-950 text-neutral-100`}
      >
        <aside></aside>
        {children}
      </body>
    </html>
  );
}
